# Generated by Django 5.0.7 on 2024-07-21 03:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogsTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='blog_imgs/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('body', models.CharField(max_length=10000)),
                ('type', models.CharField(choices=[('Tech', 'Technology'), ('Dev', 'Development'), ('Fin', 'Finance'), ('AI', 'Artificial Intelligence'), ('GD', 'Graphic Designing'), ('GD', 'Game Development')], max_length=4)),
            ],
        ),
    ]
